#!/sbin/sh
# Written by @ambasadii and @corsicanu

# Common partitions/blocks (auto-detection)
VENDOR=$(resolve_link $(find /dev/block/platform -type l -iname vendor)) && echo_log "VENDOR=$VENDOR"

# Mount necessary partitions
mount /vendor

ff=/vendor/etc/floating_feature.xml

sed -i -- '/SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_EDGE_LIGHT/d' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\    <SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_EDGE_LIGHT>TRUE</SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_EDGE_LIGHT>' $ff

sed -i -- '/SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ZERO_PAGE_PACKAGE_NAMES/d' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\    <SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ZERO_PAGE_PACKAGE_NAMES>com.google.android.googlequicksearchbox,com.samsung.android.app.spage</SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ZERO_PAGE_PACKAGE_NAMES>' $ff

sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_ACCESSIBILITY_SUPPORT_DIRECTION_LOCK>TRUE</SEC_FLOATING_FEATURE_ACCESSIBILITY_SUPPORT_DIRECTION_LOCK>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_AUDIO_SUPPORT_PSEUDO_DUAL_SPEAKER>TRUE</SEC_FLOATING_FEATURE_AUDIO_SUPPORT_PSEUDO_DUAL_SPEAKER>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_CONFIG_DYN_RESOLUTION_CONTROL>WQHD,FHD,HD</SEC_FLOATING_FEATURE_COMMON_CONFIG_DYN_RESOLUTION_CONTROL>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DUAL_SPEAKER>TRUE</SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DUAL_SPEAKER>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DEFAULT_ON_DOLBY_IN_GAME>TRUE</SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DEFAULT_ON_DOLBY_IN_GAME>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DOLBY_GAME_PROFILE>TRUE</SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DOLBY_GAME_PROFILE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_CAMERA_CONFIG_THRESHOLD_FOR_LOW_BATTERY>1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_THRESHOLD_FOR_LOW_BATTERY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AVATAR>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AVATAR>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_CAMERA_SUPPORT_DOWNLOAD_EFFECT>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_DOWNLOAD_EFFECT>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE>people,task,circle,panel,-edgefeeds,debug,search,phonecolor</SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_CONFIG_ONEHAND_MODE_POLICY>Enabled;GestureType</SEC_FLOATING_FEATURE_COMMON_CONFIG_ONEHAND_MODE_POLICY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_BIXBY>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_BIXBY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_CONVENTIONAL_MODE>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_CONVENTIONAL_MODE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_ELASTIC_PLUGIN>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_ELASTIC_PLUGIN>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_FLASH_NOTIFICATION>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_FLASH_NOTIFICATION>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_SAFETYCARE>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_SAFETYCARE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_SAMSUNG_MARKETING_INFO>FALSE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_SAMSUNG_MARKETING_INFO>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_SECUREUI_LANDSCAPE>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_SECUREUI_LANDSCAPE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_SERVICEBOX>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_SERVICEBOX>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_SMART_SWITCH>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_SMART_SWITCH>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_ULTRA_POWER_SAVING>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_ULTRA_POWER_SAVING>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_WCDMA_INSLAVE>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_WCDMA_INSLAVE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_SUPPORT_HIGH_PERFORMANCE_MODE>TRUE</SEC_FLOATING_FEATURE_COMMON_SUPPORT_HIGH_PERFORMANCE_MODE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_CONTACTS_SUPPORT_INDEX_SCROLL>TRUE</SEC_FLOATING_FEATURE_CONTACTS_SUPPORT_INDEX_SCROLL>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_CONTACTS_SUPPORT_MESSAGE_LOGS>TRUE</SEC_FLOATING_FEATURE_CONTACTS_SUPPORT_MESSAGE_LOGS>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_SCREEN_RECORDER>TRUE</SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_SCREEN_RECORDER>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GALLERY_SUPPORT_MORE_ALBUM>TRUE</SEC_FLOATING_FEATURE_GALLERY_SUPPORT_MORE_ALBUM>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GALLERY_SUPPORT_MOVE_COPY_ALBUM_THUMBNAIL>TRUE</SEC_FLOATING_FEATURE_GALLERY_SUPPORT_MOVE_COPY_ALBUM_THUMBNAIL>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GALLERY_SUPPORT_SLOW_FAST_MOTION_EXPORT>TRUE</SEC_FLOATING_FEATURE_GALLERY_SUPPORT_SLOW_FAST_MOTION_EXPORT>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GALLERY_SUPPORT_STORYEDITOR>4</SEC_FLOATING_FEATURE_GALLERY_SUPPORT_STORYEDITOR>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_CAPTURED_BLUR>TRUE</SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_CAPTURED_BLUR>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_DEFAULT_GAMELAUNCHER_ENABLE>TRUE</SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_DEFAULT_GAMELAUNCHER_ENABLE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_PARTIAL_BLUR>TRUE</SEC_FLOATING_FEATURE_GRAPHICS_SUPPORT_PARTIAL_BLUR>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_HELP_CONFIG_THEME_TYPE>K</SEC_FLOATING_FEATURE_HELP_CONFIG_THEME_TYPE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ANIMATION_TYPE>HighEnd</SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ANIMATION_TYPE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_LAUNCHER_SUPPORT_CLOCK_LIVE_ICON>TRUE</SEC_FLOATING_FEATURE_LAUNCHER_SUPPORT_CLOCK_LIVE_ICON>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_LCD_SUPPORT_AMOLED_DISPLAY>TRUE</SEC_FLOATING_FEATURE_LCD_SUPPORT_AMOLED_DISPLAY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_LCD_SUPPORT_NATURAL_SCREEN_MODE>TRUE</SEC_FLOATING_FEATURE_LCD_SUPPORT_NATURAL_SCREEN_MODE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_LOCKSCREEN_SUPPORT_FLOATING_SHORTCUT>TRUE</SEC_FLOATING_FEATURE_LOCKSCREEN_SUPPORT_FLOATING_SHORTCUT>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_LOCKSCREEN_SUPPORT_SIMPLE_PIN>TRUE</SEC_FLOATING_FEATURE_LOCKSCREEN_SUPPORT_SIMPLE_PIN>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MMFW_SUPPORT_DOLBY_AUDIO>TRUE</SEC_FLOATING_FEATURE_MMFW_SUPPORT_DOLBY_AUDIO>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MMFW_SUPPORT_MOV>TRUE</SEC_FLOATING_FEATURE_MMFW_SUPPORT_MOV>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MMFW_SUPPORT_MUSIC_ALBUMART_3DAUDIO>TRUE</SEC_FLOATING_FEATURE_MMFW_SUPPORT_MUSIC_ALBUMART_3DAUDIO>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MMFW_SUPPORT_MUSIC_AUTO_RECOMMENDATION>TRUE</SEC_FLOATING_FEATURE_MMFW_SUPPORT_MUSIC_AUTO_RECOMMENDATION>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MMFW_SUPPORT_SMARTFITTING>TRUE</SEC_FLOATING_FEATURE_MMFW_SUPPORT_SMARTFITTING>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_COVER_FLOW_NEXT_PREV_VI>TRUE</SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_COVER_FLOW_NEXT_PREV_VI>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_SCREEN_OFF_MUSIC>TRUE</SEC_FLOATING_FEATURE_MUSICPLAYER_SUPPORT_SCREEN_OFF_MUSIC>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_RIL_SUPPORT_MOBILE_DATA_ONLY>TRUE</SEC_FLOATING_FEATURE_RIL_SUPPORT_MOBILE_DATA_ONLY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_CONFIG_BRAND_NAME>Essential Galaxy</SEC_FLOATING_FEATURE_SETTINGS_CONFIG_BRAND_NAME>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DYN_RESOLUTION_CONTROL>WQHD,FHD,HD</SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DYN_RESOLUTION_CONTROL>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_DEFAULT_DOUBLE_TAP_TO_SLEEP>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_DEFAULT_DOUBLE_TAP_TO_SLEEP>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_AUTO_BRIGTNESS>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_AUTO_BRIGTNESS>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_AUTOMATIC_BRIGHTNESS_DETAIL>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_AUTOMATIC_BRIGHTNESS_DETAIL>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_DEFAULT_DOUBLE_TAP_TO_WAKE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_DEFAULT_DOUBLE_TAP_TO_WAKE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_DRIVING_MODE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_DRIVING_MODE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_EASY_MODE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_EASY_MODE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_EXTERNAL_APP_SETTINGS>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_EXTERNAL_APP_SETTINGS>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_FUNCTION_KEY_MENU>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_FUNCTION_KEY_MENU>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_DOUBLE_TAP>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_DOUBLE_TAP>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PALM_SWIPE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PALM_SWIPE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PALM_TOUCH>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PALM_TOUCH>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PAN>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PAN>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PAN_TO_BROWSE_IMAGE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PAN_TO_BROWSE_IMAGE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PICK_UP>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PICK_UP>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PICK_UP_TO_CALL_OUT>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_PICK_UP_TO_CALL_OUT>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_SHAKE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_SHAKE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_TILT>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_TILT>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_TRUN_OVER>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION_TRUN_OVER>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_SEPERATE_LOCK_AND_SECURITY>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_SEPERATE_LOCK_AND_SECURITY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_S_PEN_HOVERING>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_S_PEN_HOVERING>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_SURFACE>TRUE</SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_SURFACE>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_VOICECALL_SUPPORT_GLOBAL_NETWORK>TRUE</SEC_FLOATING_FEATURE_VOICECALL_SUPPORT_GLOBAL_NETWORK>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_VOICECALL_SUPPORT_MOBILE_DATA_SETTINGS>TRUE</SEC_FLOATING_FEATURE_VOICECALL_SUPPORT_MOBILE_DATA_SETTINGS>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_WEATHER_SUPPORT_DETAIL_CITY_VIEW>TRUE</SEC_FLOATING_FEATURE_WEATHER_SUPPORT_DETAIL_CITY_VIEW>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_COMMON_CONFIG_MULTIWINDOW_TRAY>FALSE</SEC_FLOATING_FEATURE_COMMON_CONFIG_MULTIWINDOW_TRAY>' $ff
sed -i -- '/<SecFloatingFeatureSet>/ a\        <SEC_FLOATING_FEATURE_AUDIO_CONFIG_SOUNDALIVE_VERSION>eq_knob,eq_custom,uhq_switch,uhq_level,adapt,spk_stereo,dvfs_860000,tube,concert</SEC_FLOATING_FEATURE_AUDIO_CONFIG_SOUNDALIVE_VERSION>' $ff